version: '3'

services:
  localstack: # LocalStack container
    image: localstack/localstack:4.10.0
    ports:
      # Now only required if you need to access LocalStack from the host
      - "127.0.0.1:4566:4566"
      # Now only required if you need to access LocalStack from the host
      - "127.0.0.1:4510-4559:4510-4559"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
    networks:
      - ls

  review-collector:
    image: teixeirafernando/review-collector:latest
    container_name: review-collector
    environment:
      AWS_ENDPOINT: http://localstack:4566
    depends_on:
      localstack:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - ls

  review-analyzer:
    image: teixeirafernando/review-analyzer:latest
    container_name: review-analyzer
    environment:
      AWS_ENDPOINT: http://localstack:4566
    depends_on:
      localstack:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - ls


  frontend-review:
    image: teixeirafernando/frontend-review:latest
    container_name: frontend-review
    ports:
      - "3000:80"
    networks:
      - ls

networks:
  ls:
    driver: bridge