
version: '3'

services:
  review-collector:
    image: teixeirafernando/review-collector:latest
    environment:
      - AWS_ACCESSKEY=${AWS_ACCESSKEY}
      - AWS_SECRETKEY=${AWS_SECRETKEY}
    container_name: review-collector
    ports:
      - "8080:8080"

  review-analyzer:
    image: teixeirafernando/review-analyzer:latest
    environment:
      - AWS_ACCESSKEY=${AWS_ACCESSKEY}
      - AWS_SECRETKEY=${AWS_SECRETKEY}
    container_name: review-analyzer
    ports:
      - "8081:8081"

  frontend-review:
    image: teixeirafernando/frontend-review:latest
    container_name: frontend-review
    ports:
      - "3000:80"

